{{- if .Values.observability.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operations-center.fullname" . }}-prometheus
  labels:
    {{- include "operations-center.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  selector:
    {{- include "operations-center.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  ports:
    - port: {{ .Values.observability.prometheus.service.port }}
      targetPort: 9090
{{- end }}
