{{- if and .Values.observability.tempo.enabled .Values.observability.tempo.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "operations-center.fullname" . }}-tempo
  labels:
    {{- include "operations-center.labels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.observability.tempo.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.observability.tempo.persistence.size }}
{{- end }}
