@operationsCenterApiHostAddress = http://localhost:5000

GET {{operationsCenterApiHostAddress}}/health
Accept: application/json

###

GET {{operationsCenterApiHostAddress}}/ready
Accept: application/json

###
