apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: operations-center-seq-data
  namespace: operations-center
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
