apiVersion: v1
kind: Service
metadata:
  name: operations-center-web
  namespace: operations-center
spec:
  type: ClusterIP
  selector:
    app: operations-center-web
  ports:
    - port: 80
      targetPort: 80
